### ISSUE TITLE
Enable GitHub Pages for tern-tools/tern-rest-api

### ISSUE THREAD

**Issue by kairoaraujo** [tern-tools/tern-rest-api#4]
Enabling the Github Pages for the `tern-tools/tern-rest-api` will give the user our Rest API Documentation access.

An example is available in http://kairo.eti.br/tern-rest-api/

This can be simply enabled by following the steps:` github.com/tern-tools/tern-rest-api > settings > pages > 'select folder docs/'`

The current PR #3 has the tests and instructions for updating the documentation.

**Comment by rnjudge** [comment]
Done!
![Screen Shot 2022-03-30 at 10 21 54 AM](https://user-images.githubusercontent.com/12040351/160894456-13d35e7f-b660-427d-adef-59579e6ebf08.png)
